apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-dev

resources:
  # Shared resources (ConfigMap, Secret for all services)
  - ../../../../../k8s/base/shared
  # Service-specific resources
  - ../../base

images:
  - name: frontend
    newTag: local

replicas:
  - name: frontend
    count: 1
