apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-dev

resources:
  - ../../base

images:
  - name: frontend
    newName: 212clab/wealist-frontend
    newTag: v1

replicas:
  - name: frontend
    count: 1
