apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealist-local

resources:
  - ../../base

images:
  - name: video-service
    newName: 212clab/wealist-video-service
    newTag: v1

replicas:
  - name: video-service
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: video-service-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: "dev"
